### ISSUE TITLE
problem (SCG 0.5.7)

### ISSUE THREAD

**Issue by ghzaly** [ccamara/blender-architecture-scripts#13]
how can i fix these problems ( i'm using blender 2.79 )

<img width="943" alt="screenshot_47" src="https://user-images.githubusercontent.com/42313095/44000476-ee6a8e80-9e28-11e8-936f-8580573fc255.png">

**Comment by ccamara** [comment]
I'm afraid I can't help you with the provided information. Please note that: 

1. This repo is an outdated compilation of several blender add-ons
2. I am not the developer of any of the add-ons that can be found here


I suggest you update the add-ons to the last version and check if it solves the problem. If not, please identify the add-on that is causing you that error and write its developer providing as much information as you can, such as blender version, add-on version, what did you do that raised the problem and what did you expect to happen.

Good luck!
